### ISSUE TITLE
Reducing the amount of tabs

### ISSUE THREAD

**Issue by Flaflo** [OYIon/LiveSharp#97] opened 2020-11-04 14:59 UTC
LiveSharp opens a lot of tabs.
This is really redudant, why does it not preserve one tab for one project.
Everytime I rebuild it, a new tab is spawned which is really annoying.

Is there anything I can do about it?

Thanks :)

**Comment by ionoy** [comment] 2020-11-05 11:32
Hi @Flaflo 

A new tab should open only when you start a different project from the one you were developing before. If you just rebuild the same project, there shouldn't be any new tabs.

Also, you can use `--hide-dashboard` option to not open any tabs altogether.

**Comment by Flaflo** [comment] 2020-11-05 15:24
Weill if I just re-run the project a new tab opens, and its not just me having this problem.

**Comment by ionoy** [comment] 2020-11-06 07:21
Can you describe your exact steps? Maybe I'm missing something.

What I tried to do was:

1) Start `livesharp`
2) Build project
3) Run
4) Two tabs open up, LiveSharp Dashboard and the project itself
5) Stop the project
6) Full rebuild
7) Run again
8) One tab opens up, and it's the project one

Also, what LiveSharp Server version are you on?

**Comment by Flaflo** [comment] 2020-11-13 09:55
We do exactly your steps described, but sometimes the tab livesharp opens and the connections times out and it opens another tab on another localhost port

**Comment by ChristianWeyer** [comment] 2021-03-08 13:50
I can see similar behavior @ionoy - and the `--hide-dashboard` does not work for me (at all).
I am using Server 1.7.2.0

**Comment by ChristianWeyer** [comment] 2021-03-09 17:42
Ah, I see you released a new version of the Server @ionoy - it seems the issue is now fixed for me with the `--hide-dashboard` problem.
Will need to test more on my side.

Thanks!

**Comment by devpikachu** [comment] 2021-04-28 07:42
Hey @ionoy !
I've noticed a similar behaviour on a Blazor WASM + ASP.NET WebAPI project. Running the two at the same time, both with LiveSharp enabled, upon refreshing the tab containing the Blazor WASM project, a new LiveSharp Dashboard opens for the Blazor WASM project.

Steps:
1. Build projects
2. Debug them with LiveSharp
3. 3 tabs open: 2 Dashboards, 1 project
4. Refresh (F5) the project tab
5. An additional dashboard tab opens

This was on the latest public build. I will be testing later today on the latest alpha, to see if the behaviour still persists.

**Comment by devpikachu** [comment] 2021-04-28 08:06
Can confirm, this is no longer the case on 2.0.4-alpha.

**Closed as completed** 2021-07-20 07:21 UTC
